config/routes.rb
Rails.application.routes.draw do
  resources :fan_arts
  resources :followups
  resources :posts
  resources :properties
  #resources :stances
  resources :purposes
  resources :move_effects
  resources :inputs
  resources :characters
  resources :moves
  devise_for :users
  resources :profiles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :stances do
    collection do
      post :restore_moves
      post 'stances/:id' => 'stances#restore_moves'
      get 'stances/:id' => 'stances#backup_all_moves'
      get ':id' => 'stances#destroy_all_moves'
    end
  end

  root to: 'characters#index'
end

app/models/move.rb
class Move < ApplicationRecord
  validate :custom_validation
  
  before_destroy :destroy_extensions

  private def custom_validation

    if !self.parent.blank?
      if (self.parent.extensions.select { |m| m.id != self.id && m.persisted? && m.input == self.input && m.cancel_input == self.cancel_input && m.parent_id == self.parent_id}.count > 0 )
        byebug
        self.errors[:base] << "Another Extensions of this moves parent already has the same input and the cancel input. This is not allowed"
      end

      if self.parent.stance_id != self.stance_id
        byebug
        self.errors[:base] << "Stance must be the same as parent move. Parent's Stance: #{self.parent.stance.name}"
      end

    else
      
      if (self.stance.moves.select { |m| m.persisted? && m.input == self.input && m.cancel_input == self.cancel_input && m.parent_id == self.parent_id}.count > 0 )
        byebug
        self.errors[:base] << "Another move already has the same input and the cancel input. This is not allowed."
      end
    end
    
  end

  def destroy_extensions
    self.extensions.destroy_all
  end

  belongs_to :character
  
  # STANCES
  belongs_to :stance
  
  has_many :transition_stances
  has_many :stance_transitions, :through => :transition_stances, :source => :stance
  
  # MOVE EFFECTS
  has_many :hit_effects
  has_many :counter_hit_effects
  has_many :block_effects
  
  has_many :effects_hit,         :through => :hit_effects,         :source => :move_effect
  has_many :effects_counter_hit, :through => :counter_hit_effects, :source => :move_effect
  has_many :effects_block,       :through => :block_effects,       :source => :move_effect
  
  # MOVE PURPOSES
  has_many :move_purposes
  has_many :purposes, :through => :move_purposes
  
  # MOVE PROPERTIES
  has_many :move_properties
  has_many :properties, :through => :move_properties
  
  # EXTENSION
#   has_many :move_extensions, foreign_key: :extension_id, class_name: MoveExtension.to_s
#   has_many :extensions, through: :move_extensions, source: :extension
#
#   # followee_follows "names" the Follow join table for accessing through the followee association
#   has_many :move_parents, foreign_key: :parent_id, class_name: MoveExtension.to_s
#   # source: :followee matches with the belong_to :followee identification in the Follow model
#   has_many :parents, through: :move_parents, source: :parent
  has_many :extensions, class_name: "Move", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Move", optional: true
  
#  has_many :followers, foreign_key: :follower_id , class_name: "Friendship"
  has_many :preceding_move_options, foreign_key: :followup_move_id, class_name: "Followup"
  has_many :preceding_moves, through: :preceding_move_options, source: :preceding_move
#  has_many :followed, through: :followers
#  has_many :followup_moves, through: :preceding_moves

#  has_many :followed, foreign_key: :followed_id, class_name: "Friendship"
  has_many :followup_move_options, foreign_key: :preceding_move_id, class_name: "Followup"
  has_many :followup_moves, through: :followup_move_options, source: :followup_move
  
#  has_many :followers, through: :followed
#  has_many :preceding_moves, through: :followup_moves
  
  def eldest_move 
    em = self
    loop do
      break if em.parent == nil
      em = em.parent
    end
    return em
  end
  
  # This method calculates the complete input of the string until selected move
  def complete_input_array
    currMove = self
    inputArray = [currMove]
    while currMove.parent != nil
    	currMove = currMove.parent
    	inputArray << currMove
    end
    return inputArray
  end

  # This method returns true if the move jails all the way to the parent move, some moves can jail after the first hit
  def true_jails_on_hit? 
    true_jails = true
    em = self
    loop do
      
      break if em.parent == nil
      
      if !em.jails_on_hit?
        true_jails = false
        break
      end
      
      em = em.parent
    end
    return true_jails
  end

  def true_hit_startup 
    if self.parent.blank?
      return startup
    else
      m = self
      while m.jails_on_hit?
        m = m.parent
      end
      return m.startup
    end
  end
  
  def total_damage_on_hit
    total = 0
    total_damage_on_hit_array.each do |dmg|
      total += dmg
    end
    return total
  end
  
  def all_jailing_extensions
    jailing_extensions = []
    extensions.each do |e|
      child_jailing_extensions = e.all_jailing_extensions
      if child_jailing_extensions.count > 0 
        jailing_extensions << child_jailing_extensions
      elsif
        if e.true_jails_on_hit?
          jailing_extensions << e
        end
      end
    end
    return jailing_extensions
  end
  
  def total_damage_on_hit_array
    em = self
    dmg = []
    loop do
      dmg << em.hit_damage.to_i
      break if em.parent == nil
      em = em.parent
    end
    return dmg
  end
  
  def jails_on_hit?
    effects_hit.where(name: "Jails").count > 0
  end
  def jails_on_counter_hit?
    effects_counter_hit.where(name: "Jails").count > 0
  end
  def jails_on_block?
    effects_block.where(name: "Jails").count > 0
  end
  
  def is_grab?
    return properties.select { |prop| prop.name == "Grab" }.count > 0
  end

  def is_punisher?
    return purposes.select { |prop| prop.name == "Punisher" }.count > 0
  end

  def launches_on_hit?
    return effects_hit.select { |eff| (eff.name == "Launch" || eff.name == "Launch Screwed") }.count > 0
  end
  
  def hit_effects_presentable_strings
    a = ""
    b = ""
    effects_hit.each do |he|
      x = he.name.split('(')

      a = x[0]

      if x.count > 1
        b = "(" + x[1]
      end
      
    end

    return a, b
  end

  def counter_hit_effects_presentable_strings
    a = ""
    b = ""
    effects_counter_hit.each do |he|
      x = he.name.split('(')

      a = x[0]

      if x.count > 1
        b = "(" + x[1]
      end
      
    end

    return a, b
  end


  def track_direction
    if properties.where(name: "Tracks Left").count > 0
      return "Left"
    elsif properties.where(name: "Tracks Right").count > 0
      return "Right"
    elsif properties.where(name: "Tracks Both").count > 0
      return "Both"
    else
      return "None"
    end
  end
  
  # SORT METHODS
  
  def self.input_priority_array
    inputPriorityArray = ["1","2","3","4","1+2","2+3","3+4","1+4","1+3","2+4","f","df","d","db","b","ub","u","uf"]
  end
  
  def self.sort_by_priority_array(array_to_sort, priority_array)
    arr_temp = array_to_sort#moves.to_a
    
    array_length = arr_temp.size
    return array_to_sort if array_length <= 1
    
    loop do
      # we need to create a variable that will be checked so that we don't run into an infinite loop scenario.
      swapped = false
      
      # subtract one because Ruby arrays are zero-index based
      (array_length-1).times do |i|
        
        
        # MY LOGIC
        inputPriorityArray = priority_array
        
        m1Array = arr_temp[i].eldest_move.input.split(",")
        m2Array = arr_temp[i+1].eldest_move.input.split(",")
      
        m1Index = 0
        m2Index = 0
        x = 0
      
        loop do
          m1Index = inputPriorityArray.index(m1Array[x])
          m2Index = inputPriorityArray.index(m2Array[x])
        
          break if x >= m1Array.count || x >= m2Array.count | m1Index != m2Index
        
          x += 1
        end
        # MY LOCIC END
        
        
        if m1Index > m2Index
          arr_temp[i], arr_temp[i+1] = arr_temp[i+1], arr_temp[i]
          swapped = true
        end
      end

      break if not swapped
    end
    
    arr_temp
  end
  
  def backup_dict()

    dict = {
      :input => input, 
      :name => name,

      #:stance => stance.name,
      :parent => parent == nil ? "" : parent.input,
      :cancel_input => cancel_input,

      #Frames
      :startup => startup,
      :on_block => on_block,
      :on_hit => on_hit,
      :on_counter_hit => on_counter_hit,
      
      #damage info
      :hit_damage =>         hit_damage,
      :conter_hit_damage => conter_hit_damage,
      :hit_level =>         hit_level,

      :counter => counter,

      :move_purpose => purposes.map { |p| p.name },
      :properties =>   properties.map { |p| p.name },

      :effects_hit =>         effects_hit.map { |p| p.name },
      :effects_counter_hit => effects_counter_hit.map { |p| p.name },
      :effects_block =>       effects_block.map { |p| p.name },

    }

    if extensions.blank? 
      
      return dict
      
    else
      
      ext_json_array = []

      extensions.each do |extension|
         ext_json_array << extension.backup_dict
      end
      
      dict[:child_moves] = ext_json_array
      return dict

    end

    

  end
end

app/controllers/moves_controller.rb
 class MovesController < ApplicationController
  before_action :set_move, only: [:show, :edit, :update, :destroy]
  # DEVISE CHECK
  before_action :authenticate_user!, :only => [:new, :edit, :create, :destroy, :index]

  

  # GET /moves
  # GET /moves.json
  def index
    @moves = Move.all
  end

  # GET /moves/1
  # GET /moves/1.json
  def show
    @followup = Followup.new(preceding_move_id:@move.id)
    
    # ON BLOCK
    hit_mv_array = []
    @move.character.moves.each do |move|
      if move.eldest_move.startup.to_i - @move.on_block.to_i < 10 and move.jails_on_hit?
        hit_mv_array << move
      elsif move.parent == nil
        if move.eldest_move.startup.to_i - @move.on_block.to_i < 10
          hit_mv_array << move
        end
      end
    end
    @on_block_moves = hit_mv_array
    
    # ON HIT
    hit_mv_array = []
    @move.character.moves.each do |move|
      if move.eldest_move.startup.to_i - @move.on_hit.to_i < 10 and move.jails_on_hit?
        hit_mv_array << move
      elsif move.parent == nil
        if move.eldest_move.startup.to_i - @move.on_hit.to_i < 10
          hit_mv_array << move
        end
      end
    end
    @on_hit_moves = hit_mv_array
    
    # ON COUNTER HIT
    hit_mv_array = []
    @move.character.moves.each do |move|
      if move.eldest_move.startup.to_i - @move.on_counter_hit.to_i < 10 and move.jails_on_hit?
        hit_mv_array << move
      elsif move.parent == nil
        if move.eldest_move.startup.to_i - @move.on_counter_hit.to_i < 10
          hit_mv_array << move
        end
      end
    end
    @on_counter_hit_moves = hit_mv_array

  end

  # GET /moves/new
  def new
    if params[:copy_from] != nil
      cf = Move.find(params[:copy_from])
      @move = Move.new(:name => cf.name, 
                       :input =>  cf.input,
                       :hit_level => cf.hit_level,
                       :hit_damage => cf.hit_damage,
                       :conter_hit_damage => cf.conter_hit_damage,
                       :startup => cf.startup,
                       :on_block => cf.on_block,
                       :on_hit => cf.on_hit,
                       :on_counter_hit => cf.on_counter_hit)
    else
      @move = Move.new
    end
      

    if params["parent_move_id"].blank?
      @stance_id = params[:stance_id]
    else
      @stance_id = Move.find(params["parent_move_id"]).stance_id
    end
    
  end

  # GET /moves/1/edit
  def edit
    @stance_id = @move.stance_id
    @stance_id = params[:stance_id]
  end

  # POST /moves
  # POST /moves.json
  def create
    @move = Move.new(move_params)

    respond_to do |format|
      if @move.save
        
        if params[:create_and_add_new]
          format.html { 
            redirect_to controller: 'moves', action: 'new', char_id: @move.character.id, notice: 'Move was successfully created.'
           }
        elsif params[:create_and_add_extension]
          format.html { 
            redirect_to controller: 'moves', action: 'new', char_id: @move.character.id, parent_move_id:@move.id, notice: 'Move was successfully created.'
          }
        else
          format.html { redirect_to @move.character, notice: 'Character was successfully created.' }
        end
        
        #format.html { redirect_to @move.character }#redirect_to @move, notice: 'Move was successfully created.' }
        format.json { render :show, status: :created, location: @move }
      else
        format.html { render :new }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moves/1
  # PATCH/PUT /moves/1.json
  def update
    
    respond_to do |format|
      if @move.update(move_params)
        if params[:update_and_add_new]
          format.html { 
            redirect_to controller: 'moves', action: 'new', char_id: @move.character.id, notice: 'Move was successfully created.'
           }
        elsif params[:update_and_add_extension]
          format.html { 
            redirect_to controller: 'moves', action: 'new', char_id: @move.character.id, parent_move_id:@move.id, notice: 'Move was successfully created.'
          }
        else
          format.html { redirect_to @move.character, notice: 'Character was successfully created.' }
        end
        
        #format.html { redirect_to @move.character }#redirect_to @move, notice: 'Move was successfully updated.' }
        format.json { render :show, status: :ok, location: @move }
      else
        format.html { render :edit }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end
 
  # DELETE /moves/1
  # DELETE /moves/1.json
  def destroy
    @move.destroy
    respond_to do |format|
      format.html { redirect_to @move.character, notice: 'Move was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move
      @move = Move.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def move_params
      params.require(:move).permit(:name, :input, :startup, :on_block, :on_hit, :on_counter_hit, :hit_damage, :conter_hit_damage, :hit_level, :counter, :character_id, :cancel_input, :stance_transition_input, :type, :stance_id, :parent_id, :property_ids => [], :stance_transition_ids => [], :effects_hit_ids => [], :effects_counter_hit_ids => [], :effects_block_ids => [], :purpose_ids => [])
    end
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/moves/edit.html.erb
<h1>Editing Move</h1>

<%= render 'form', move: @move %>

<%= link_to 'Show', @move %> |
<%= link_to 'Back', moves_path %>

app/views/moves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moves</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moves.each do |move| %>
      <tr>
        <td><%= if (move.character == nil) 
					"<Not Assigned>" 
				else 
					move.character.name 
				end  %> > <%= move.name %></td>
        <td><%= link_to 'Show', move %></td>
        <td><%= link_to 'Edit', edit_move_path(move) %></td>
        <td><%= link_to 'Destroy', move, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Move', new_move_path %>

app/views/moves/new.html.erb
<h1>New Move</h1>

<%= render 'form', move: @move %>

<%= link_to 'Back', moves_path %>

app/views/moves/show.html.erb
<script>
	$(function(){ $("#tabs").tabs() });
	$(function(){ $("#tabs2").tabs() });
	$(function(){ $("#tabs_most_damage").tabs() });
</script>
<p id="notice"><%= notice %></p>

< <%= link_to @move.character.name, @move.character %> <br>
<p>
	<h3><%= @move.name %></h3>
	<%= render 'components/moveView', move: @move, show_paths: false%>
</p>

<%= link_to 'Edit', edit_move_path(@move) %> |
<%= link_to 'Back', character_path(@move.character) %>

<div class="stuff">
	<div id="tabs">
	  <ul>
	    <li><a href="#tabs-1">COMMENTS</a></li>
	    <li><a href="#tabs-2">FOLLOWUPS</a></li>
	    <li><a href="#tabs-3">MIXED WITH</a></li>
	  </ul>
	  <div style="clear:both"></div>
	  <div class="tab_bar" id="tabs-1">
		  <h2 class="section_heading_large">  Comments </h2>
			<div class="options_container">
				<%= link_to "Create New Post", new_post_url(:character_id=>@move.character.id, :post_type=>"M0") %>
			</div>
			<%= render 'components/posts_list_view', :char_id=>@move.character.id, :post_type=>"M0" %>
	  </div>
	  
	  <div id="tabs-2">
		  <h2 class="section_heading_large"> Followups </h2>
		  <div id="tabs2">
			  <div class="list_section">
				  <ul>
					  <li><a href="#on_hit">On Hit</a></li>
					  <li><a href="#on_counter_hit">On Counter Hit</a></li>
					  <li><a href="#on_block">On Block</a></li>
				  </ul>
				  <div style="clear:both"></div>
			  		
					<% def a(status) %>
					<% Followup.where(:preceding_move_id=>@move.id,:hit_status=>status).each do |followup| %>
						
						<% move = Move.find(followup.followup_move_id) %>
						<% if followup.is_guaranteed %>
							<span style="color:red">guaranteed</span>
						<% end %>
							<%= render 'components/moveView', move: move, show_paths: false %>
						<% end %>
					<% end %>
					
				  <div id="on_hit">
						<div class="tab_followups_title">  Followup Moves: </div>
						<div class="tab_followups_value">
							<% a(1) %>
						</div>
					
				  </div>
			  
				  <div id="on_counter_hit">
					<div class="tab_followups_title">  Followup Moves: </div>
					<div class="tab_followups_value">
						<% a(2) %>
					</div>
				  </div>
			  
				  <div id="on_block">
					<div class="tab_followups_title">  Followup Moves:  </div>
					<div class="tab_followups_value">
						<% a(0) %>
					</div>
				</div>
			 </div>
			 <div clss="new_section">
				 <div class="move_area" style="float:left">
					 <div class="move_selector_container" style="display:block;width: 40%; height: 100%;">
					 	<div style="height:80%;width:300px;background: #FFF;
									padding: 20px;margin: 0 auto;margin-top: 50px;">
					 		<%= render 'components/movesListView', view_style:"mini", char_id:@move.character.id %> 
					 	</div>
					 </div>
				 </div>
				 
				 <div class="form_area" style="float:left">
			 		 <%= render 'followups/form', followup: @followup %>
				 </div>
				 <div class="clr"></div>
			 </div>
		  </div>
	  </div>
	  
	  <div id="tabs-3">
	    <h2 class="section_heading_large">  Mixed With </h2>
	  </div>
	</div>
</div>

<script>
	$(document).ready(function(){
		$(".selectable_move_container").click(function() {
			var move_id = $(this).attr("move_id");
			$('#followup_followup_move_id').val(move_id);
		});
	});
	
	$('#insert_move_link').on('click',
	    function () {
			console.log("LOG " + $(".move_selector_container").length);
			$(".move_selector_container")[0].style.display = "block";
//			console.log("LOG " + $(".move_selector_container")[0].style.display);
	    }
	);
</script>