config/routes.rb
Rails.application.routes.draw do
  resources :fan_arts
  resources :followups
  resources :posts
  resources :properties
  #resources :stances
  resources :purposes
  resources :move_effects
  resources :inputs
  resources :characters
  resources :moves
  devise_for :users
  resources :profiles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :stances do
    collection do
      post :restore_moves
      post 'stances/:id' => 'stances#restore_moves'
      get 'stances/:id' => 'stances#backup_all_moves'
      get ':id' => 'stances#destroy_all_moves'
    end
  end

  root to: 'characters#index'
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :moves
  has_many :stances
  
  has_many :posts
  
  has_many :fan_arts
  
  def sorted_stances
    sort_by_priority_array(stances.to_a, ["Standing", 
      "Full Crouch", 
      "While Standing", 
      "While Running",
      "Back Turned",
      "Side Step Right",
      "Side Step Left",
      "On Ground (Face Up Feet towards)", 
      "On Ground (Face Down Feet towards)", 
      "On Ground (Face Up Feet away)", 
      "On Ground (Face Down Feet away)"])
  end
  
  # def moves_sorted_by_input
#     arr_temp = moves.to_a
#
#     array_length = arr_temp.size
#     return moves if array_length <= 1
#
#     loop do
#       # we need to create a variable that will be checked so that we don't run into an infinite loop scenario.
#       swapped = false
#
#       # subtract one because Ruby arrays are zero-index based
#       (array_length-1).times do |i|
#
#
#         # MY LOGIC
#         inputPriorityArray = Move.input_priority_array
#
#         m1Array = arr_temp[i].input.split(",")
#         m2Array = arr_temp[i+1].input.split(",")
#
#         m1Index = 0
#         m2Index = 0
#         x = 0
#
#         loop do
#           m1Index = inputPriorityArray.index(m1Array[x])
#           m2Index = inputPriorityArray.index(m2Array[x])
#
#           break if x >= m1Array.count || x >= m2Array.count | m1Index != m2Index
#
#           x += 1
#         end
#         # MY LOCIC END
#
#
#         if m1Index > m2Index
#           arr_temp[i], arr_temp[i+1] = arr_temp[i+1], arr_temp[i]
#           swapped = true
#         end
#       end
#
#       break if not swapped
#     end
#
#     arr_temp
#   end
  
  def moves_sorted_by_input
    Move.sort_by_priority_array(moves.to_a, Move.input_priority_array)
  end
  
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]
  # DEVISE CHECK
  before_action :authenticate_user!, :only => [:new, :edit, :create, :destroy]

  before_action :check_character_status, :only => [:show]

  def check_character_status
    redirect_to(root_path) unless (@character.publish.to_i == 1 || user_signed_in?)
  end
  
  # GET /characters
  # GET /characters.json
  def index

    if !user_signed_in?
      @characters = Character.where.not(publish:"-1")
    else
      @characters = Character.all
    end

    if !params[:sort].blank?
      
      if params[:sort] == "tier"
        @characters = @characters.sort_by{ |c| ["S++", "S+", "S","A", "B", "C"].index(c.tier) }
      elsif params[:sort] == "diff"
        @characters = @characters.sort_by{ |c| ["5/5", "4/5", "3/5","2/5", "1/5"].index(c.difficulty) }
      else
        @characters = @characters.sort_by{ |c| c.name }
      end

    else
      @characters = @characters.sort_by{ |c| c.name }
    end
    
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)
    
    respond_to do |format|
      if @character.save
        
        if params[:create_without_stances] == nil
          
          # Create Related Stances
          ["Standing", 
            "Full Crouch", 
            "While Standing", 
            "While Running",
            "Back Turned",
            "Side Step Right",
            "Side Step Left",
            "On Ground (Face Up Feet towards)", 
            "On Ground (Face Down Feet towards)", 
            "On Ground (Face Up Feet away)", 
            "On Ground (Face Down Feet away)"].each do |stanceName|
            
              stance = @character.stances.create(name:stanceName)
              
              if if params[:create_without_moves] == nil
                if stanceName == "Standing" || stanceName == "While Standing"
                  ["1","2","3","4","1+2","3+4"].each do |moveInput|
                    Move.create(name:stanceName+" "+moveInput, input:moveInput, character:@character, stance:stance).save!
                  end
                end
            
                if stanceName == "Standing"
                  ["f,1", "b,1", "d,1", "df,1",
                    "f,2","b,2", "d,2", "df,2",
                    "f,3","b,3", "d,3",
                    "f,4","b,4", "d,4", "uf,4"].each do |mi|
          
                    Move.create(name:stanceName+" "+mi, input:mi, character:@character, stance:stance).save!
                  end
                end
              end
              end
          end
        end
        
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
        
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.require(:character).permit(:name, :wiki_link, :full_image_link, :thumb_image_link, :gameplay, :fighting_style, :archetype, :difficulty, :tier, :publish, :strengths, :weaknesses, :movement)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: character, local: true) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% character.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :wiki_link %>
    <%= form.text_field :wiki_link %>
  </div>
  
  <div class="field">
    <%= form.label :full_image_link %>
    <%= form.text_field :full_image_link %>
  </div>
  
  <div class="field">
    <%= form.label :thumb_image_link %>
    <%= form.text_field :thumb_image_link %>
  </div>
  
  <div class="field">
    Fighting Style: <%= form.text_field :fighting_style %>
  </div>
  <div class="field">
    Archetype: <%= form.text_field :archetype %>
  </div>
  <div class="field">
    Difficulty: <%= form.text_field :difficulty %>
  </div>
  <div class="field">
    Tier: <%= form.text_field :tier %>
  </div>
  <div class="field">
    Publish: <%= form.text_field :publish %>
  </div>

  <div class="field">
    <%= form.label :strengths %>
    <%= form.text_field :strengths %>
  </div>

  <div class="field">
    <%= form.label :weaknesses %>
    <%= form.text_field :weaknesses %>
  </div>

  <div class="field">
    <%= form.label :movement %>
    <%= form.text_field :movement %>
  </div>
  
  <div class="field">
    <%= form.label :gameplay %>
    <%= form.text_area :gameplay %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
	<%= submit_tag 'Create Without Moves', name: 'create_without_moves' %>
	<%= submit_tag 'Create Without Stances', name: 'create_without_stances' %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<div class="main_container">
	
	<div class="page_title">Choose Your Character</div>

	<div class="character_filter_options">
		<input type="text" id="search_box" onkeyup="myFunction()" placeholder="Search names or archetype" class="filter_text_field">
		<%if false %>
		<%= select_tag("sort_select", options_for_select(["Sort by Name","Sort by Tier","Sort by Archetype","Sort by Difficulty"]), :class=>"filter_select" ) %>
		<% end %>
		<%# select_tag("difficulty_select", options_for_select(["1","2","3","4","5"]), :prompt => "Difficulty", :class=>"filter_select" ) %>

		<%# select_tag("tier_select", options_for_select(["S++","S+","S","A","B","C"]), :prompt => "Tier", :class=>"filter_select" ) %>

		<%# select_tag("arcehtype_select", options_for_select(["Mishima", "Mixup","Rushdown","Oppression","Meter","Confusion","Poking","Keep Out"]), :prompt => "Archetype", :class=>"filter_select" ) %>
	</div>
	
	<% if user_signed_in? %>
		<div class=""><%= link_to 'New Character', new_character_path, {:class=>"button"}%></div>
	<% end %>

	<div class="characters_container">
		
		<% @characters.each do |character| %>
			<div class="character_card"
			<% if character.publish.to_i == -1 %> 
			style="border: 2px solid red;" 
			<% elsif character.publish.to_i == 0 %>
			style="border: 2px dotted red;"
			<% end %>
			>
				<div class="character_image">
					<% fan_arts = character.fan_arts.where(:is_main=>1) %>
					<% offset = rand(fan_arts.count) %>
					<% image = fan_arts.offset(offset).first %>
					<% if image == nil %>
					<img src="<%= character.thumb_image_link %>" width="100" height ="100">
					<% else %>
					<%= render 'components/fan_art_display', image:image %>
					<% end %>
				</div>
				<div class="character_name">
					<div class="archtype_div">
						<%= character.archetype %>
					</div>
					<div class="name_value_div">
						<% if character.publish.to_i == 1 || user_signed_in? %>
							<%= link_to character.name, character %>
						<% else %>
							<%= link_to character.name, "#", data: { confirm: 'This character has not yet been implemented. Thankyou for your patience.' } %>
						<% end %>
					</div>
					<div class="archetype_value_div" style="padding-top:10px">
						(<%= character.fighting_style %>)
					</div>
					<!--<a href="<%= character.wiki_link %>">(wiki)</a>-->
				</div>
				
				<% if user_signed_in? %>
				<div class="character_actions">
					<%= link_to 'Edit', edit_character_path(character) %> |
					<%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %>
				</div>
				<% end %>

				<div class="character_desc">
					<%= character.gameplay %>
				</div>
				<div class="character_info_div">
					<div class="info_col">
						<div class="info_col_value">
							<%= character.movement %>
						</div>
						<div class="info_col_title">
							Movement
						</div>
					</div>
					<div class="info_col">
						<div class="info_col_value">
							<%= character.difficulty %>/5
						</div>
						<div class="info_col_title">
							Difficulty
						</div>
					</div>
					<div class="info_col">
						<div class="info_col_value">
							<% if character.tier == "S" || character.tier == "S+" || character.tier == "S++"  %>
								<span style="color:#FFD700">
							<% else %>
								<span>
							<% end %>
								<%= character.tier %>
							</span>
							
						</div>
						<div class="info_col_title">
							Tier
						</div>
					</div>
					<div class="clr"></div>
				</div>
				
			</div>
		<% end %>
		<div style="clear:both"></div>
	</div>
</div>

<script>
	// This method makes the search bar work
	function myFunction() {
		
		// Declare variables
		var input, filter, ul, li, a, i, txtValue;
		input = document.getElementById('search_box');
		filter = input.value.toUpperCase();
		
		var parent_div = $('.characters_container:visible')[0]
		move_div = $(parent_div).find(".name_value_div");
		arc_div = $(parent_div).find(".archtype_div");

		// Loop through all list items, and hide those who don't match the search query
		for (i = 0; i < move_div.length; i++) {
			
			nameValue = move_div[i].textContent || move_div[i].innerText;
			archValue = arc_div[i].textContent || arc_div[i].innerText;
			console.log(" + " + archValue);
			inputValue = $(move_div[i])//.parentElement.parentElement.attr('input');
			iv = inputValue.text();//inputValue[0].parentElement.parentElement).attr('input')
			
			if (nameValue.toUpperCase().indexOf(filter) > -1 || iv.toUpperCase().startsWith(filter) ||
				archValue.toUpperCase().indexOf(filter) > -1
				) {
				
				move_div[i].parentElement.parentElement.style.display = "block";
				$(move_div[i].parentElement.parentElement).css('padding-left','0px');
			} else {
				console.log("OH");
				move_div[i].parentElement.parentElement.style.display = "none";
			}
		}
	}
</script>

<%# render 'components/interpView', text: "[*h]this is a test text.[/h] move below: [@3] this move is considered one of the best moves in the game because it allowes the user to go to his home and bring a bazooka to desctroy everything. also in order to counter the user you must use the following move [@6] [*b]and finally a video to prove it:[/b] [^6L8ZB7blOW8] The older raiden only figured out his folly because he saw up his [*b]ass:[/b] [%https://www.destructoid.com/ul/591403-fujin-trailer-mk-11-aftermath.jpg,https://i2-prod.dailystar.co.uk/tech/gaming/article21977988.ece/ALTERNATES/s1200c/0_Mortal-Kombat-11.jpg,
https://cdn-prod.mortalkombat.com/static/share.jpg] [;] source: [$Albert Einstine,http://www.alberteinstine.com] this is me"%>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>