config/routes.rb
Rails.application.routes.draw do
  resources :fan_arts
  resources :followups
  resources :posts
  resources :properties
  #resources :stances
  resources :purposes
  resources :move_effects
  resources :inputs
  resources :characters
  resources :moves
  devise_for :users
  resources :profiles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :stances do
    collection do
      post :restore_moves
      post 'stances/:id' => 'stances#restore_moves'
      get 'stances/:id' => 'stances#backup_all_moves'
      get ':id' => 'stances#destroy_all_moves'
    end
  end

  root to: 'characters#index'
end

app/models/stance.rb
class Stance < ApplicationRecord
  before_destroy :destroy_associated_moves

  belongs_to :character
  has_many :moves
  
  has_many :stance_transitions, through: :moves, :class_name => Move.to_s
  
  def destroy_associated_moves
    self.moves.destroy_all
  end
  
  def parent_moves
    Move.sort_by_priority_array(moves.select {|move| move.parent == nil }.to_a, Move.input_priority_array)
    #arr = moves.select {|move| move.parent == nil }
    
    #arr.each_with_index do |i, m|
    #  print "-------------------------------------------------- " + m.to_s + " --->" + i.input + "\n"
    #end
    #arr.sort_by{ |move| Move.input_priority_array.index(move.input) }
      
  end

  def child_moves
    Move.sort_by_priority_array(moves.select {|move| move.extensions.count <= 0 || !move.cancel_input.blank?}.to_a, Move.input_priority_array)
  end
  def punisher_moves(startup)
    # get all parent moves that have same frame startup as provided
    # go through each extension and if any jails add them to the final array else add the parent move
    #moves.select{ |move| move.starup.to_i == startup.to_i }.each do |move| {}
    
    arr = moves.select{ |move| move.true_hit_startup.to_i == startup.to_i }.sort_by { |m| m.total_damage_on_hit }
    final_array = []
    if arr.count > 0 
      max_dmg_move = arr.first
      arr.each do |move|
        if move.launches_on_hit? || move.is_punisher?
          final_array << move
        elsif move.total_damage_on_hit > max_dmg_move.total_damage_on_hit
          max_dmg_move = move
        end
      end

      final_array << max_dmg_move

      return final_array
    else
      return []
    end
    #launches_on_hit
    # final_moves = []
    # parent_moves.select{ |move| move.startup.to_i == startup.to_i }.each do |move|
    #   jailing_extensions = move.all_jailing_extensions
    #   if jailing_extensions.count > 0
    #     final_moves.concat jailing_extensions
    #   else
    #     final_moves << move
    #   end
    # end
    
    # # Finally we need to extract the moves with highest damage and highest frames
    # return [final_moves.sort_by { |m| m.total_damage_on_hit }.first, final_moves.sort_by { |m| m.is_punisher? }]#[final_moves.sort_by { |move| move.total_damage_on_hit }.last, final_moves.sort_by { |move| move.on_hit }.last]
  end
  
  def moves_sorted_by_input
    Move.sort_by_priority_array(child_moves.to_a, Move.input_priority_array)
    #Move.sort_by_priority_array(moves.to_a, Move.input_priority_array)
  end
  
  # def moves_sorted_by_input
  #   arr_temp = moves.to_a
  #
  #   array_length = arr_temp.size
  #   return moves if array_length <= 1
  #
  #   loop do
  #     # we need to create a variable that will be checked so that we don't run into an infinite loop scenario.
  #     swapped = false
  #
  #     # subtract one because Ruby arrays are zero-index based
  #     (array_length-1).times do |i|
  #
  #
  #       # MY LOGIC
  #       inputPriorityArray = ["1","2","3","4","f","b","d","1+2","3+4","uf","df"]
  #
  #       m1Array = arr_temp[i].input.split(",")
  #       m2Array = arr_temp[i+1].input.split(",")
  #
  #       m1Index = 0
  #       m2Index = 0
  #       x = 0
  #
  #       loop do
  #         m1Index = inputPriorityArray.index(m1Array[x])
  #         m2Index = inputPriorityArray.index(m2Array[x])
  #
  #         break if x >= m1Array.count || x >= m2Array.count | m1Index != m2Index
  #
  #         x += 1
  #       end
  #       # MY LOCIC END
  #
  #
  #       if m1Index > m2Index
  #         arr_temp[i], arr_temp[i+1] = arr_temp[i+1], arr_temp[i]
  #         swapped = true
  #       end
  #     end
  #
  #     break if not swapped
  #   end
  #
  #   arr_temp
  # end

  
  def backup_moves
    json_strings = []
    parent_moves.each do |move|
      json_strings << move.backup_dict.to_json
    end
    return "[" + json_strings.join(",") + "]"
  end

  def restore(json_string)
    
    
  end
end

app/controllers/stances_controller.rb
class StancesController < ApplicationController
  before_action :set_stance, only: [:show, :edit, :update, :destroy]
  # DEVISE CHECK
  before_action :authenticate_user!, :only => [:new, :edit, :create, :destroy, :show, :index]
  

  # GET /stances
  # GET /stances.json
  def index
    @stances = Stance.all
  end

  # GET /stances/1
  # GET /stances/1.json
  def show
  end

  # GET /stances/new
  def new
    @stance = Stance.new
  end

  # GET /stances/1/edit
  def edit
    @stance = Stance.find(params[:id])
  end

  # POST /stances
  # POST /stances.json
  def create
    @stance = Stance.new(stance_params)

    respond_to do |format|
      if @stance.save
        format.html { redirect_to @stance, notice: 'Stance was successfully created.' }
        format.json { render :show, status: :created, location: @stance }
      else
        format.html { render :new }
        format.json { render json: @stance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stances/1
  # PATCH/PUT /stances/1.json
  def update
    respond_to do |format|
      if @stance.update(stance_params)
        format.html { redirect_to @stance, notice: 'Stance was successfully updated.' }
        format.json { render :show, status: :ok, location: @stance }
      else
        format.html { render :edit }
        format.json { render json: @stance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stances/1
  # DELETE /stances/1.json
  def destroy
    @stance.destroy
    respond_to do |format|
      format.html { redirect_to stances_url, notice: 'Stance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_all_moves
    @stance = Stance.find(params[:id])

    if @stance.moves.destroy_all
      flash[:notice] = "All Moves in Stance \"#{@stance.name}\" were destroyed."
      
    else
      flash[:notice] = "Unable to destroy moves in Stance \"#{@stance.name}\": #{@stance.errors}."
    end
    
    redirect_to @stance.character
  end

  def backup_all_moves
    @stance = Stance.find(params[:id])
    render json: @stance.backup_moves
  end

  def save_move_from_dict(move_dict, parent_move)

    move = @stance.moves.where(:input => move_dict["input"]).select{ |m| move_dict["parent"].blank? ? m.parent == nil : (m.parent == nil ? false : m.parent.input == move_dict["parent"])}.first
      
      if move == nil
        move = @stance.moves.create()
      end

      move.name = move_dict["name"].blank? ? move.name : move_dict["name"]

      move.input     = move_dict["input"] 
      move.hit_level = move_dict["hit_level"].blank? ? move.hit_level : move_dict["hit_level"]

      
      move.cancel_input = move_dict["cancel_input"].blank? ? move.cancel_input : move_dict["cancel_input"]

      
      move.startup = move_dict["startup"].blank? ? move.startup : move_dict["startup"]
      move.on_block = move_dict["on_block"].blank? ? move.on_block : move_dict["on_block"]
      move.on_hit = move_dict["on_hit"].blank? ? move.on_hit : move_dict["on_hit"]
      move.on_counter_hit = move_dict["on_counter_hit"].blank? ? move.on_counter_hit : move_dict["on_counter_hit"]

      
      move.hit_damage = move_dict["hit_damage"].blank? ? move.hit_damage : move_dict["hit_damage"]
      move.conter_hit_damage = move_dict["conter_hit_damage"].blank? ? move.conter_hit_damage : move_dict["conter_hit_damage"]
      
       
      move.counter = move_dict["counter"].blank? ? move.counter : move_dict["counter"]

      # ADDING RELATIONSHIPS

      move.character = @stance.character
      
      #:move_purpose => MovePurpose.where('lower(name) = ?', bb["move_purpose"][0].downcase).first,
      if !move_dict["move_purpose"].blank?
        move_dict["move_purpose"].each do |purpose|
          purp = Purpose.where('lower(name) = ?', purpose.downcase).first
          if !purp.blank?
            move.purposes << purp
          end
        end
      end

      #:properties =>   properties.map { |p| p.name },
      if !move_dict["properties"].blank?
        move_dict["properties"].each do |property|
          prop = Property.where('lower(name) = ?', property.downcase).first
          if !prop.blank?
            move.properties << prop
          end
        end
      end

      #:effects_hit =>         effects_hit.map { |p| p.name },
      if !move_dict["effects_hit"].blank?
        move_dict["effects_hit"].each do |item|
          val = MoveEffect.where('lower(name) = ?', item.downcase).first
          if !val.blank?
            move.effects_hit << val
          end
        end
      end
      #:effects_counter_hit => effects_counter_hit.map { |p| p.name },
      if !move_dict["effects_counter_hit"].blank?
        move_dict["effects_counter_hit"].each do |item|
          val = MoveEffect.where('lower(name) = ?', item.downcase).first
          if !val.blank?
            move.effects_counter_hit << val
          end
        end
      end
      #:effects_block =>       effects_block.map { |p| p.name },
      if !move_dict["effects_block"].blank?
        move_dict["effects_block"].each do |item|
          val = MoveEffect.where('lower(name) = ?', item.downcase).first
          if !val.blank?
            move.effects_block << val
          end
        end
      end

      #Set parent move
      if !parent_move.blank?
        move.parent = parent_move
      end
      
      if move.save
        if !move_dict["child_moves"].blank?

          move_dict["child_moves"].each do |cm|
            save_move_from_dict(cm, move)
          end
        end

        return move
      end
  end

  def dict_from_json(json_string)
    begin
      
      parsed_json = JSON.parse json_string

      return parsed_json

    rescue JSON::ParserError
      
      print("Unable to parse json")

      return nil
    end
  end

  def restore_moves

    @stance = Stance.find(params[:selected_stance])

    parsed_json = dict_from_json(params[:moves_json])
    
    if parsed_json != nil
      
      parsed_json.each do |move_dict|
        save_move_from_dict(move_dict, nil)
      end

    else
      flash[:nocice] = "Unable to parse json"
      format.html { render :edit }
      return
    end
    

    respond_to do |format|
      format.html { render :edit }
      # if @move.save
      #   format.html { redirect_to @move, notice: 'Move was successfully created.' }
      #   format.json { render :show, status: :created, location: @move }
      # else

      #   format.html { render :edit }
      #   format.json { render json: @move.errors, status: :unprocessable_entity }
      # end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stance
      @stance = Stance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stance_params
      params.require(:stance).permit(:name, :desc, :character_id)
    end
end

app/helpers/stances_helper.rb
module StancesHelper
end

app/views/stances/_form.html.erb
<%= form_with(model: stance, local: true) do |form| %>
  <% if stance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stance.errors.count, "error") %> prohibited this stance from being saved:</h2>

      <ul>
        <% stance.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if defined?(@move) %>
  <% if @move.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@move.errors.count, "error") %> prohibited this stance from being saved:</h2>

      <ul>
        <% @move.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div>

	<% if @stance.character_id %>
	    <div class="field">
	  	  <%= form.select :character_id, options_from_collection_for_select(Character.all, 'id', 'name', @stance.character_id) %>
	    </div>
	<% else %>
	    <div class="field">
	  	  <%= form.select :character_id, options_from_collection_for_select(Character.all, 'id', 'name', params[:char_id]) %>
	    </div>
	<% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<h1>Restore Form</h1>
<%= form_for stance, url: {:controller => "stances", action: "restore_moves", params: {id: stance.id}}, method: :post do |f|%>

<% moves_json = stance.backup_moves#stance.moves.first.backup_json#  %>
<%= select_tag('selected_stance', options_from_collection_for_select(stance.character.stances.all, 'id', 'name', params[:id])) %>

<%= text_area_tag(:moves_json, moves_json, size: '50x10') %>
<%= f.submit "Submit" %>
<%end%>

app/views/stances/edit.html.erb
<h1>Editing Stance</h1>

<%= render 'form', stance: @stance %>

<%= link_to 'Show', @stance %> |
<%= link_to 'Back', stances_path %>

app/views/stances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stances</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Character</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stances.each do |stance| %>
      <tr>
        <td><%= stance.id %>. <%= stance.name %></td>
        <td><%= stance.desc %></td>
        <td><%= stance.character_id %></td>
        <td><%= link_to 'Show', stance %></td>
        <td><%= link_to 'Edit', edit_stance_path(stance) %></td>
        <td><%= link_to 'Destroy', stance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stance', new_stance_path %>

app/views/stances/new.html.erb
<h1>New Stance</h1>

<%= render 'form', stance: @stance %>

<%= link_to 'Back', stances_path %>

app/views/stances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stance.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @stance.desc %>
</p>

<p>
  <strong>Character:</strong>
  <%= @stance.character_id %>
</p>

<%= link_to 'Edit', edit_stance_path(@stance) %> |
<%= link_to 'Back', stances_path %>